#!/usr/bin/env bash

# alias
alias dev='cd ~/coding/'
alias pac='sudo pacman -S'
alias yayi='yay -S'
alias yayr='yay -R'
alias pacr='sudo pacman -R'
alias update='sudo pacman -Syu && yay'

#utils
alias ls='eza --icons --color=always --group-directories-first'
alias cat='bat'
alias cd='z'
